#小程序用户
CREATE TABLE `fdc_procedures_user` (
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `PHONE` varchar(11) NOT NULL COMMENT '手机号',
  `WX_NAME` varchar(100) DEFAULT NULL COMMENT '微信名称',
  `USER_NAME` varchar(30) DEFAULT NULL COMMENT '用户名称',
  `RECOMMENDATINO_PHONE` varchar(11) DEFAULT NULL COMMENT '我的推荐人手机号',
  `HEAD_URL` varchar(200) DEFAULT NULL COMMENT '头像URL', 
  `RECOMMENDATINO_COUNT` smallint(6) DEFAULT 0 COMMENT '我的推荐人数',
  `LOOK_HOUSE_COUNT` smallint(6) DEFAULT 0 COMMENT '我的看房次数',
  `COMMISSION_PRICE` varchar(10) DEFAULT 0 COMMENT '佣金金额',

  `CREATE_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `phone` (`PHONE`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='小程序用户';

#小程序看房记录
CREATE TABLE `fdc_look_house_log` (
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `PHONE` varchar(11) NOT NULL COMMENT '手机号',
  `WX_NAME` varchar(100) DEFAULT NULL COMMENT '微信名称',
  `USER_NAME` varchar(30) DEFAULT NULL COMMENT '用户名称',
  `REAL_ESTATE_NO` varchar(12) NOT NULL COMMENT '楼盘编号',
  `REAL_ESTATE_NAME` varchar(50) DEFAULT NULL COMMENT '楼盘名称',
  `CREATE_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '看房时间',
  `CREATE_USER_ID` varchar(10) NOT NULL COMMENT '创建人ID',
  `END_DATE` datetime DEFAULT NULL COMMENT '结束时间',
  PRIMARY KEY (`ID`),
  KEY `IDX_phone` (`PHONE`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='小程序看房记录';

#小程序成交记录
CREATE TABLE `fdc_transaction_log` (
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `ORDER_NO` varchar(12) NOT NULL COMMENT '成交单号',
  `PHONE` varchar(11) NOT NULL COMMENT '手机号',
  `DIRECT_RECOMMEND_PHONE` varchar(11) DEFAULT NULL COMMENT '直接推荐人手机号',
  `INDIRECT_RECOMMEND_PHONE` varchar(11) DEFAULT NULL COMMENT '间接推荐人手机号',

  `WX_NAME` varchar(100) DEFAULT NULL COMMENT '微信名称',
  `USER_NAME` varchar(30) DEFAULT NULL COMMENT '用户名称',
  `REAL_ESTATE_NO` varchar(12) NOT NULL COMMENT '楼盘编号',
  `REAL_ESTATE_NAME` varchar(50) DEFAULT NULL COMMENT '楼盘名称',
  `HUXING_NO` varchar(12) NOT NULL COMMENT '户型编号',
  `TRANSACTION_PRICE` varchar(10) NOT NULL COMMENT '成交金额',
  `CREATE_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '成交时间',
  `CREATE_USER_ID` varchar(10) NOT NULL COMMENT '创建人ID',
  PRIMARY KEY (`ID`),
  KEY `IDX_phone` (`PHONE`) USING BTREE,
  UNIQUE KEY `orderNo` (`ORDER_NO`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='小程序成交记录';

#小程序佣金流水
CREATE TABLE `fdc_commission` (
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `ORDER_NO` varchar(12) NOT NULL COMMENT '成交单号',
  `COMMISSION_NO` varchar(12) NOT NULL COMMENT '佣金单号',
  `COMMISSION_PHONE` varchar(11) NOT NULL COMMENT '手机号',
  `WX_NAME` varchar(100) DEFAULT NULL COMMENT '微信名称',
  `USER_NAME` varchar(30) DEFAULT NULL COMMENT '用户名称',
  `COMMISSION_PRICE` varchar(10) NOT NULL COMMENT '佣金金额',
  `REAL_ESTATE_NAME` varchar(50) DEFAULT NULL COMMENT '楼盘名称',
  `HUXING_NO` varchar(12) DEFAULT NULL COMMENT '户型编号',
  `TRANSACTION_PRICE` varchar(10) DEFAULT NULL COMMENT '成交金额',
  `CREATE_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `CREATE_USER_ID` varchar(10) NOT NULL COMMENT '创建人ID',
  PRIMARY KEY (`ID`),
  KEY `IDX_orderNo` (`ORDER_NO`) USING BTREE,
  UNIQUE KEY `commissionNo` (`COMMISSION_NO`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='小程序佣金';

#小程序提现申请
CREATE TABLE `fdc_withdrawals_apply` (
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `APPLY_NO` varchar(12) NOT NULL COMMENT '申请单号',
  `COMMISSION_NO` varchar(12) NOT NULL COMMENT '佣金单号',

  `PHONE` varchar(11) NOT NULL COMMENT '手机号',
  `WX_NAME` varchar(100) DEFAULT NULL COMMENT '微信名称',
  `USER_NAME` varchar(30) DEFAULT NULL COMMENT '用户名称',
  `WITHDRAWALS_PRICE` varchar(10) NOT NULL COMMENT '提现金额',
  `BANK_NO` varchar(50) NOT NULL COMMENT '银行卡号',
  `BANK_NAME` varchar(100) NOT NULL COMMENT '开卡行名称',
  `ACCOUNT_NAME` varchar(30) NOT NULL COMMENT '开户人名称',
  `BANK_ADDRESS` varchar(200) DEFAULT NULL COMMENT '开户支行地址',
  `WITHDRAWALS_STATUS` char(1) DEFAULT '1' COMMENT '提现状态:1申请中、2已提现、3提现失败',
  `FAIL_REASONS` varchar(200) DEFAULT NULL COMMENT '失败原因',
  `CREATE_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`ID`),
  KEY `IDX_phone` (`PHONE`) USING BTREE,
  UNIQUE KEY `applyNo` (`APPLY_NO`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='小程序提现申请';

#小程序转账凭证
CREATE TABLE `fdc_transfers_certificate` (
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `APPLY_NO` varchar(12) NOT NULL COMMENT '申请单号',
  `COMMISSION_PHONE` varchar(11) NOT NULL COMMENT '用户手机号',
  `WX_NAME` varchar(100) DEFAULT NULL COMMENT '微信名称',
  `USER_NAME` varchar(30) DEFAULT NULL COMMENT '用户名称',
  `COMMISSION_PRICE` varchar(10) NOT NULL COMMENT '转账佣金金额',
  `TRANSFERS_CERTIFICATE_URL` varchar(200) DEFAULT NULL COMMENT '转账凭证图片URL',
  `CREATE_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`ID`),
  KEY `IDX_phone` (`PHONE`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='小程序转账凭证';

#小程序用户推荐表
CREATE TABLE `fdc_procedures_user_recommendation` (
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `PHONE` varchar(11) NOT NULL COMMENT '手机号',
  `WX_NAME` varchar(100) DEFAULT NULL COMMENT '推荐人微信名称',
  `USER_NAME` varchar(30) DEFAULT NULL COMMENT '推荐人用户名称',

  `BELOW_PHONE` varchar(11) DEFAULT NULL COMMENT '下级推荐人手机号',
  `CREATE_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`ID`),
  KEY `IDX_phone` (`PHONE`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='小程序用户推荐表';

#小程序轮播图
CREATE TABLE `fdc_banner` (
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `BANNER_URL` varchar(200) NOT NULL COMMENT 'banner图片地址',
  `BANNER_TYPE` char(1) DEFAULT '1' COMMENT '1图片，2视频',
  `BANNER_SORT` tinyint(4) DEFAULT NULL COMMENT '序号',
  `GO_TO_URL` varchar(200) DEFAULT NULL COMMENT '跳转地址',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='小程序轮播图';

#小程序楼盘
CREATE TABLE `fdc_real_estate` (
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `REAL_ESTATE_NO` varchar(12) NOT NULL COMMENT '楼盘编号',
  `REAL_ESTATE_NAME` varchar(50) NOT NULL COMMENT '楼盘名称',
  `ADDRESS` varchar(200) DEFAULT NULL COMMENT '楼盘地址',
  `START_PRICE` varchar(10) DEFAULT NULL COMMENT '上线金额',
  `END_PRICE` varchar(10) DEFAULT NULL COMMENT '下线金额',
  `TELEPHONE_CONTACT` varchar(12) DEFAULT NULL COMMENT '联系电话',
  `PREFERENTIAL_INFORMATION` varchar(500) DEFAULT NULL COMMENT '优惠信息',
  `RECOMMENDATION_INCENTIVES` varchar(500) DEFAULT NULL COMMENT '推介奖励',
  `COMMISSION_RULES` varchar(500) DEFAULT NULL COMMENT '佣金细则',
  `OPEN_HOURS_DATE` DATE DEFAULT NULL COMMENT '开盘时间',
  `DELIVERY_DATE` DATE DEFAULT NULL COMMENT '交楼时间',
  `PROPERTY_TYPE` varchar(70) DEFAULT NULL COMMENT '产权类型',
  `PROPERTY` varchar(50) DEFAULT NULL COMMENT '产权',
  `PROPERTY_COMPANY` varchar(100) DEFAULT NULL COMMENT '物业公司',
  `START_AREA_INTERVAL` varchar(10) DEFAULT NULL COMMENT '开始面积区间',
  `END_AREA_INTERVAL` varchar(10) DEFAULT NULL COMMENT '结束面积区间',
  `START_HUXING_INTERVAL` varchar(10) DEFAULT NULL COMMENT '开始户型区间',
  `END_HUXING_INTERVAL` varchar(10) DEFAULT NULL COMMENT '结束户型区间',
  `REAL_ESTATE_INTRODUCTION` varchar(500) DEFAULT NULL COMMENT '楼盘介绍',
  `REAL_ESTATE_ASSORT` varchar(500) DEFAULT NULL COMMENT '项目配套',
  `REAL_ESTATE_COMMERCE` varchar(500) DEFAULT NULL COMMENT '项目商业',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `realEstateNo` (`REAL_ESTATE_NO`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='小程序楼盘';

#小程序楼盘相册
CREATE TABLE `fdc_real_estate_banner` (
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `REAL_ESTATE_NO` varchar(12) NOT NULL COMMENT '楼盘编号',
  `BANNER_URL` varchar(200) NOT NULL COMMENT 'banner图片地址',
  `BANNER_TYPE` char(1) DEFAULT '1' COMMENT '1图片，2视频',

  PRIMARY KEY (`ID`),
  KEY `IDX_realEstateNo` (`REAL_ESTATE_NO`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='小程序楼盘相册';

#小程序户型
CREATE TABLE `fdc_real_huxing` (
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `REAL_ESTATE_NO` varchar(12) NOT NULL COMMENT '楼盘编号',
  `HUXING_NO` varchar(12) NOT NULL COMMENT '户型编号',
  `BANNER_URL` varchar(200) NOT NULL COMMENT '户型图片地址',
  `IS_MAJOR_HUXING` char(1) DEFAULT '1' COMMENT '是否主打户型：1是0否',
  `ROOM_NUM` tinyint(4) DEFAULT NULL COMMENT '房数',
  `OFFICE_NUM` tinyint(4) DEFAULT NULL COMMENT '厅数',
  `CONSTRUCTION_AREA` varchar(10) DEFAULT NULL COMMENT '建筑面积',
  `START_FLOOR` varchar(10) DEFAULT NULL COMMENT '开始楼层',
  `END_FLOOR` varchar(10) DEFAULT NULL COMMENT '结束楼层',
  `HUXING_INTRODUCTION` varchar(10) DEFAULT NULL COMMENT '户型介绍',
  PRIMARY KEY (`ID`),
  KEY `IDX_realEstateNo` (`REAL_ESTATE_NO`) USING BTREE,
  UNIQUE KEY `huxingNo` (`HUXING_NO`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='小程序户型';

#小程序用户银行卡
CREATE TABLE `fdc_procedures_user_bank` (
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `PHONE` varchar(11) NOT NULL COMMENT '手机号',
  `BANK_NO` varchar(50) NOT NULL COMMENT '银行卡号',
  `BANK_NAME` varchar(100) NOT NULL COMMENT '开卡行名称',
  `ACCOUNT_NAME` varchar(30) NOT NULL COMMENT '开户人名称',
  `BANK_ADDRESS` varchar(200) DEFAULT NULL COMMENT '开户支行地址',
  `CREATE_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`ID`),
  KEY `IDX_phone` (`PHONE`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='用户银行卡';

Recommendation
